typography_spectrum: 0.028810066170990467
color:
  brandStrength: 0.6756498634349555
  lightness: 0.867822787258774
  saturation: 0.8562535734381527
  rhythmicContrast: 0.3712293254211545
  brandColors:
    - '#000000'
    - '#404040'
    - '#808080'
    - '#BFBFBF'
    - '#FFFFFF'
github: true
layout_spectrum: 0.9330446312669665
analytics:
  google: UA-94091815-1
author:
  name: Greenman
  email: greenman@the-organization.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a57c92d6-11da-4829-84f3-87e14848f050.png
name: Pragmatic Tarot
url: 'http://pragmatictarot.com/'
navigation:
  - name: About
    id: 9a06d6ed-e203-4769-9a30-9219224ea0f0
    type: content
  - name: Contact
    id: 1d6f94dd-51c0-415f-bcff-94614d557ed4
    type: content
  - name: Readings
    id: ad7585a0-4c7a-4c3b-8302-fb9f67c10c8a
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e25e84f7-9376-46d1-95f8-3e22890fb5fc.png
title: Tarot without superstition
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f42e5d89-ca86-477c-8b34-f23057f7f980.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f42e5d89-ca86-477c-8b34-f23057f7f980.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/f3dd975a-4dbd-4d33-94ef-57ad2d139e92.png">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/f3dd975a-4dbd-4d33-94ef-57ad2d139e92.png
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: A language of change
purpose:
  - type: internal
    label: Workshops
    item: 9605e273-62dd-4190-976c-d0b5f7c037b7
  - type: internal
    label: Book a reading
    item: ad7585a0-4c7a-4c3b-8302-fb9f67c10c8a
